# -*- coding: utf-8 -*-
"""Ownership guard on the adopted portal close route (P6-T03 / #67).

WHAT THIS FIXES. OCA `helpdesk_mgmt` ships:

    @http.route("/ticket/close", type="http", auth="user")
    def support_ticket_close(self, **kw):
        ticket = request.env["helpdesk.ticket"].sudo().search(
            [("id", "=", values["ticket_id"])])
        ...
        ticket.stage_id = values.get("stage_id")

`auth="user"` admits ANY authenticated user — including a portal user of a
different customer — and the lookup is `.sudo()`, which steps straight around
`helpdesk_ticket_rule_portal`, the very rule this platform relies on for portal
isolation. The ticket id arrives from the request. So customer A could post
customer B's ticket id and close B's ticket, and (because this module reacts to
`stage_id` in `write()`) also stamp B's first-response and flip B's SLA verdict.

That is a cross-customer IDOR in an adopted dependency. Adopting a module means
adopting its bugs: the moment we pin it, its isolation IS our isolation.

WHY AN OVERRIDE RATHER THAN A PATCH UPSTREAM. Standing Rule 1 — never modify
OCA or core code in place; the pinned tree is regenerated by `make oca` and any
edit there would be silently discarded on the next aggregation. So the guard
lives here, in our own module, where it survives a re-pin. Reported upstream is
the right follow-up, but shipping unmitigated while waiting is not.

The guard re-resolves the ticket under the CALLER's own rights before
delegating. Non-sudo means the portal record rule applies, so a foreign ticket
simply does not exist for that user and the request is refused. The parent then
does its own sudo work on a ticket we have already proven the caller may reach.
"""

from odoo import http
from odoo.http import request

from odoo.addons.helpdesk_mgmt.controllers.main import HelpdeskTicketController


class NcHelpdeskTicketController(HelpdeskTicketController):

    # Bare @http.route() re-uses the parent's route definition (path, type,
    # auth) — the Odoo idiom for overriding a controller method without
    # restating, and accidentally widening, its routing.
    @http.route()
    def support_ticket_close(self, **kw):
        """Refuse to close a ticket the caller cannot already see."""
        try:
            ticket_id = int(kw.get('ticket_id') or 0)
        except (TypeError, ValueError):
            return request.not_found()
        if not ticket_id:
            return request.not_found()

        # NOT sudo. This is the whole guard: the search runs as the caller, so
        # helpdesk_ticket_rule_portal filters a foreign ticket out and the
        # recordset comes back empty.
        visible = request.env['helpdesk.ticket'].search(
            [('id', '=', ticket_id)], limit=1)
        if not visible:
            # 404 rather than 403: telling an attacker "that exists but is not
            # yours" confirms the id, which is the thing being probed.
            return request.not_found()

        return super().support_ticket_close(**kw)
