#!/usr/bin/env bash
# =============================================================================
# assert_oca_present.sh [context]
#
# Refuse to start anything that mounts ./oca while ./oca is missing or empty.
#
# WHY THIS EXISTS. `./oca/` is GENERATED by `make oca` from the pins in
# repos.yml and is gitignored, so it does not travel with the tree. A fresh
# `git worktree` has none. docker-compose.yml mounts it anyway:
#
#     - ./oca:/mnt/oca-addons:ro
#
# Docker CREATES a missing bind-mount source as an empty directory rather than
# failing, so /mnt/oca-addons exists and contains nothing. Odoo starts happily.
# Every module depending on an OCA addon then fails to install — and, because
# odoo exits 0 on that (see assert_odoo_setup.sh), the suite goes on to report
# whatever it was measuring.
#
# Measured, from a worktree: the cron-starvation harness installs
# ncollection_saas, which depends on OCA queue_job, and reported
#
#     ❌ FAIL: arm A: the reconcile cron never ran at all within 120s
#
# The cron never ran because the module never installed. That cost a full
# invalid `verify-all` run and was initially attributed to a regression on
# develop — it was not; the only variable was the worktree (#384).
#
# Worktrees are the RIGHT way to work a second ticket without disturbing a
# colleague's checkout — CLAUDE.md Rule 14 exists because the tree and the
# stack are shared — so "do not use worktrees" is the wrong answer. Fail fast
# and say what to run instead.
#
# Exit 0 = every pinned repo is present. Exit 1 = it is not, with the fix.
# =============================================================================
set -euo pipefail

context="${1:-this stack}"
cd "$(dirname "${BASH_SOURCE[0]}")/../.."
root="$PWD"

if [ ! -r repos.yml ]; then
  # Fail closed: no pin list means we cannot know what SHOULD be there, and
  # reporting "fine" over an unreadable source of truth is how a guard becomes
  # decoration.
  echo "REFUSING: $root/repos.yml is unreadable, so ./oca cannot be verified." >&2
  exit 1
fi

# The pin list is the source of truth, not a hardcoded directory name. The two
# checks this replaces both tested `oca/mis-builder` alone, so an oca/ that was
# half-aggregated — mis-builder present, queue missing — passed them while
# still breaking every module that depends on queue_job.
expected="$(grep -oE '^\./oca/[A-Za-z0-9_.-]+' repos.yml | sed 's|^\./oca/||' | sort -u)"
if [ -z "$expected" ]; then
  echo "REFUSING: no './oca/<repo>:' targets found in repos.yml — the pin list" >&2
  echo "  changed shape and this check would silently verify nothing." >&2
  exit 1
fi

missing=""
for repo in $expected; do
  # Present AND non-empty: a half-finished `make oca`, or docker having created
  # the mount point, both leave an empty directory behind.
  if [ ! -d "oca/$repo" ] || [ -z "$(ls -A "oca/$repo" 2>/dev/null)" ]; then
    missing="$missing $repo"
  fi
done

if [ -n "$missing" ]; then
  echo "REFUSING: ./oca is missing or empty, so $context cannot work." >&2
  echo "  Missing or empty:$missing" >&2
  echo "" >&2
  echo "  Fix:  make oca" >&2
  echo "" >&2
  echo "  WHY YOU ARE SEEING THIS. ./oca/ is generated from repos.yml and is" >&2
  echo "  gitignored, so it does not travel with the tree — a fresh git" >&2
  echo "  worktree has none. Compose mounts ./oca anyway, and docker creates a" >&2
  echo "  missing bind-mount source as an EMPTY directory instead of failing." >&2
  echo "  Odoo then starts fine and every OCA-dependent module silently fails" >&2
  echo "  to install, which surfaces 20 minutes later as an unrelated timing" >&2
  echo "  or provisioning error (#384)." >&2
  echo "" >&2
  echo "  Do NOT 'fix' this with a symlink: .gitignore's rule is '/oca/', which" >&2
  echo "  matches a DIRECTORY. A symlink named oca is NOT ignored and can be" >&2
  echo "  committed by accident." >&2
  exit 1
fi
